config/routes.rb
Rails.application.routes.draw do
  resources :bookmarks
  resources :restaurants
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant

  validates_uniqueness_of :user_id, scope: :restaurant_id
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  belongs_to :creator, class_name: "User", foreign_key: "user_id", optional: true
  has_many :bookmarks
  has_many :users, through: :bookmarks

  
end

app/models/user.rb
class User < ApplicationRecord
  has_many :created_restaurants, class_name: "Restaurant"
  has_many :bookmarks
  has_many :restaurants, through: :bookmarks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  before_action :set_restaurant, only: [:edit, :show, :update, :destroy ]

  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def edit

  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to @restaurant
    else
      render :new
    end
  end

  def update

  end

  def destroy

  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :neighborhood, :street_address, :category, :tips)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  has_many :created_restaurants, class_name: "Restaurant"
  has_many :bookmarks
  has_many :restaurants, through: :bookmraks


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LocalRestaurants</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/edit.html.erb
<%= form_for @restaurant do |f| %>
<%= f.label :name %>
<%= f.text_field :name %> <br>
<%= f.label :neighborhood %>
<%= f.text_field :neighborhood %> <br>
<%= f.label :street_address %>
<%= f.text_field :street_address %> <br>
<%= f.label :category %>
<%= f.text_field :category %> <br>
<%= f.label :tips %>
<%= f.text_field :tips %> <br>
<%= f.submit %>
<% end %>

app/views/restaurants/new.html.erb
<h1>Create a New Restaurant</h1>

<%= form_for @restaurant do |f| %>
<%= f.label :name %>
<%= f.text_field :name %> <br>
<%= f.label :neighborhood %>
<%= f.text_field :neighborhood %> <br>
<%= f.label :street_address %>
<%= f.text_field :street_address %> <br>
<%= f.label :category %>
<%= f.text_field :category %> <br>
<%= f.label :tips %>
<%= f.text_field :tips %> <br>
<%= f.submit %>
<% end %>

app/views/restaurants/show.html.erb
<%= @restaurant.name %> <br>
<%= @restaurant.neighborhood %> <br>
<%= @restaurant.street_address %> <br>
<%= @restaurant.category %> <br>
<%= @restaurant.tips %>

<br> <br>

<%= link_to "Edit Restaurant", edit_restaurant_path(@restaurant) %>